scenario: '../src/examples/greenframe.cjs'
baseURL: 'https://greenframe.io'
samples: 2
projectName: 'GreenFrame'
kubeContainers:
    - 'default:app=api'
kubeDatabaseContainers:
    - 'default:app=db'
