scenario: '../src/examples/greenframe.js'
baseURL: 'https://greenframe.io'
samples: 2
distant: false
projectName: 'GreenFrame'
kubeContainers:
    - 'default:app=api'
kubeDatabaseContainers:
    - 'default:app=db'
