scenario: '../../src/examples/greenframe.cjs'
baseURL: 'https://greenframe.io'
samples: 2
projectName: 'GreenFrame'
containers:
    - 'enterprise_api'
    - 'container_broken'
databaseContainers:
    - 'enterprise_db'
