export default {
    SCENARIO_FAILED: 'SCENARIO_FAILED' as const,
    CONFIGURATION_ERROR: 'CONFIGURATION_ERROR' as const,
    THRESHOLD_EXCEEDED: 'THRESHOLD_EXCEEDED' as const,
    UNKNOWN_ERROR: 'UNKNOWN_ERROR' as const,
};
