const ERROR_CODES = {
    SCENARIO_FAILED: 'SCENARIO_FAILED',
    CONFIGURATION_ERROR: 'CONFIGURATION_ERROR',
    THRESHOLD_EXCEEDED: 'THRESHOLD_EXCEEDED',
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
};

module.exports = ERROR_CODES;
